[package]
name = "ziti_box_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
asky = "0.1.1"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["cargo", "derive"] }
color-eyre = "0.6.5"
comfy-table = "7.2.1"
dirs-next = "2.0.0"
ext4_rs = "1.3.2"
glob = "0.3.3"
gpt = "4.1.0"
once_cell = "1.21.3"
reqwest = { version = "0.12.24", features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
ziti_api = { package = "openapi", path = "./openapi" }
